config/routes.rb
Snapsbox::Application.routes.draw do
  devise_for :users

  get 'buttons/upload' => 'buttons#upload', as: :upload_buttons
  post 'buttons/import'
  
  resources :buttons do    
    resources :comments
  end
  

  root :to => 'buttons#index'

end

app/models/button.rb
class Button < ActiveRecord::Base
  paginates_per 4
  
  has_many :comments
  mount_uploader :screenshot, ScreenshotUploader

  # Associations
  belongs_to :team
  belongs_to :user
    
  after_create :get_screenshot
  after_create :create_first_comment, if: Proc.new { self.description.present? }
  
  #Validations
  validates :title, presence: true
  validates :url, presence: true
  validates_format_of :url, :with => URI::regexp(%w(http https))

  private
  def get_screenshot
    get_screenshot_task
  end

  def get_screenshot_task
    begin
      file = Tempfile.new(["#{id}_#{Time.now.to_i}".downcase, '.jpg'], 'tmp', :encoding => 'ascii-8bit')
      image = IMGKit.new(url, quality: 80).to_jpg
      file.write(image)
      file.flush
      self.screenshot = file
    rescue IMGKit::CommandFailedError
      # ERROR, NO SE PUDO GENERAR CAPTURA DE PANTALLA
    end
    self.save
    file.unlink
  end
  
  def create_first_comment
    self.comments.create(body: description, user: user )
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :button
  belongs_to :user

  # Validations
  validates_presence_of :body
  validates_presence_of :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  # Associations
  has_many :users
  has_many :buttons
  
  # Validations
  validate :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enumerize :role, in: [:member, :admin], default: :member

  # Associations
  has_many :buttons
  belongs_to :team 
  
  validate :name, uniqueness: { scope: :team_id }
  # Callbacks
  before_create :create_team
  
  # Methods
  private  
  def create_team
    
    if self.invitation_token
      self.team = User.find(self.invited_by_id).team
    else
      self.team = Team.create(name: "Default")
      self.role = :admin
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_team
  	@current_team ||= current_user.team
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:edit) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
  
  private
  def after_sign_out_path_for(resource_or_scope)
    new_session_path(resource_or_scope)
  end
end

app/controllers/buttons_controller.rb
# encoding: utf-8
class ButtonsController < ApplicationController
  layout 'application'
  respond_to :html
  respond_to :js, only: [:index]
  before_filter :find_button, only: [:show, :edit, :update, :destroy]

  def index
    respond_with collection
  end
  
  def create
    @button = current_team.buttons.build(buttons_params.merge(user: current_user))
    @button.save 
    respond_with @button
  end
  
  def update
    @button.update_attributes(buttons_params)
    respond_with @button
  end

  def collection
    @buttons = current_team.buttons.page(params[:page] || 1)
  end

  def upload 
    if request.post? and params[:bookmark]
      @results = BookmarkParser.parseFile(params[:bookmark].tempfile.path)      
      flash[:notice] = "File processed: #{@results.length} bookmarks detected."
    end
  end

  def destroy
    @button.destroy
    redirect_to buttons_url
  end

  def import
    urls = params[:urls]
    titles = params[:titles]
    sel = params[:selection]

    sel.each { |ind| Button.create({url: urls[ind.to_i], title: titles[ind.to_i], author: current_user}) }
  end

  private 
  def buttons_params
    params.require(:button).permit(:url, :title, :description)
  end

  def find_button
    @button = current_team.buttons.find params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  nested_belongs_to :button
  
  def create
  	button = current_team.buttons.find params[:button_id]
    @comment = button.comments.build(comment_params)
    @comment.save
    redirect_to button
  end

  private
  def comment_params
  	params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def foundation_type(type)
    case type
      when :warning then 'warning'
      when :alert then 'alert'
      when :notice then 'success'
      when :info then 'secondary'
      else nil
    end
  end
end

app/views/buttons/_button.html.haml
.large-3.medium-3.small-12.columns.template-wrap.left
  = link_to image_tag(button.screenshot.thumb.url), button_path(button.id)  
  %p.thumb-info
    = link_to button.title, button_path(button.id)
    by
    %span.notes= link_to button.user.name

app/views/buttons/_comment.html.haml
.row.comment
  .large-3.columns.author= comment.user.name
  .large-9.columns
    .row.date
      %em= comment.created_at
    .row.comment_body= comment.body
%hr
    
    

app/views/buttons/_form.html.haml
= simple_form_for @button ||= Button.new do |f|
  .row.right
    .small-12.columns
      
      .row
        .small-3.columns
          %label.right(for="right-label") URL
        .small-9.columns
          = f.input_field :url

      .row
        .small-3.columns
          %label.right(for="right-label") Title
        .small-9.columns
          = f.input_field :title

      .row
        .small-3.columns
          %label.right(for="right-label") Text
        .small-9.columns
          = f.input_field :description, as: :text 
    
  = f.submit 'Save', class: 'button'

app/views/buttons/edit.html.haml
%h1 Editing button

= render 'form'

= link_to 'Show', @button
\|
= link_to 'Back', buttons_path

app/views/buttons/import.html.haml
%h2 Import buttons
%p Buttons processed.
%p= link_to 'Go back', buttons_path

app/views/buttons/index.html.haml
- content_for :header do
  %h1.title Share designs you like
  %h4.subtitle (or not)

.row.buttons-row
  = render partial: 'button', collection: @buttons, as: :button

- unless @buttons.last_page?
  .row#next_page_link
    .large-12.columns#next_page= link_to_next_page(@buttons, 'Show more', remote: true, params: params, class: 'button') 

app/views/buttons/new.html.haml
%h1 New button

= render 'form'

= link_to 'Back', buttons_path

app/views/buttons/show.html.haml
- content_for :header do
  %h1
    %small Button
    = @button.title

.row.main-content
  .small-9.columns
    = link_to image_tag(@button.screenshot), @button.url, target: '_blank'
  .small-3.columns.text-left#sidebar
    %h3 Button Info:
    %ul 
      %li
        %strong URL:
        = link_to(@button.url, @button.url, rel: 'external')
      %li
        %strong Description:
        = @button.description
      %li
        %strong Posted by:
        = raw " #{link_to(@button.user.name)} at #{@button.created_at}"
      %hr
      %ul.inline-list
        %li= link_to 'Edit', edit_button_path(@button)
        %li= link_to 'Destroy', @button, :confirm => 'Are you sure?', :method => :delete
        %li= link_to 'Back', buttons_path

.row.comments
  .small-12.columns.small-centered#comments
    = render partial: 'comment', collection: @button.comments, as: :comment

.row#comment_form
  %b Write a comment
  = simple_form_for Comment.new, url: button_comments_path(@button) do |f|
    .small-8.columns.small-centered
      = f.input_field :body
      = f.submit 'Post comment', class: 'button small'
    

app/views/buttons/upload.html.haml
%h2 Import buttons
- if @results
  %p
    = check_box_tag "selection_trigger", "all", true
    %label{for: "selection_trigger"}= "Select all"

  = form_tag "#{buttons_path}/import" do
    %table.bookmarks
      - @results.each_with_index do |r, index|
        %tr
          %td
            = check_box_tag "selection[]", index, true, id: index
            = hidden_field_tag "urls[]", r[:url]
            = hidden_field_tag "titles[]", r[:title]
          %td< 
            %label{for: "#{index}"}= r[:title]
          %td<
            %a{href: "#{r[:url]}"}= r[:url]
    = submit_tag

= form_tag "#{buttons_path}/upload", multipart: true do
  %label{for: "bookmark"} Upload your bookmarks file!
  = file_field_tag 'bookmark'
  = submit_tag

app/views/layouts/_alerts.html.haml
- flash.each do |type, msg|
  - if type != :event
    .alert-box.text-center{data: {alert: ''},  class: foundation_type(type) }
      = msg
      = link_to '×', '', class: 'close'

app/views/layouts/_footer.html.haml
%footer.row.bottom
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p Content
      .large-6.columns
        %p Content

app/views/layouts/_header.html.haml
%h1 ButtonBox

app/views/layouts/_messages.html.haml
- flash.each do |type, msg|
  = content_tag :div, raw(msg), :id => "flash_#{type}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
#nav-bar.fixed
  .row
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1=link_to image_tag('/assets/logo.png'), root_path, class: 'app-logo'
        -  if current_user
          %li.toggle-topbar.menu-icon
            %a{href: "#"}
      -  if current_user
        %section.top-bar-section
          / Right Nav Section
          %ul.right          
            %li.has-dropdown
              = link_to( "Hi, #{current_user.name}")
              %ul.dropdown
                %li= link_to("Profile", edit_user_registration_path)
                %li= link_to "Invite", new_user_invitation_path
                %li= link_to("Logout", destroy_user_session_path, :method => :delete) 
            %li.has-dropdown
              = link_to 'Button actions', '#'
              %ul.dropdown
                %li= link_to 'Create Button', new_button_path
                %li= link_to 'Import Button', upload_buttons_path

app/views/layouts/_topmenu.html.haml
%p
  Hi
  =current_user.name
  !
  %br
  Team: 
  =current_user.team.id
  ( 
  = current_user.team.name
  )
  %br
  Team members:
  =current_user.team.users.count
%ul
  %li Profile
  %li= link_to "Invite", new_user_invitation_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : 'Snapsbox'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    #alerts= render 'layouts/alerts' 
    %header
      .row.header
        .large-12.columns= yield :header
      
    .row#main-content
      .small-12.columns.text-center= yield
    = javascript_include_tag "application"

  = render 'layouts/footer'